### ISSUE TITLE
community/modules/signatures/windows/antivm_generic_cpu.py error

### ISSUE THREAD

**Issue by swackhamer** [cuckoosandbox/community#135]
Getting a error with this signature.

> 2016-05-31 18:32:34,541 [lib.cuckoo.core.plugins] ERROR: Failed to run 'on_complete' of the antivm_generic_cpu signature
> Traceback (most recent call last):
>   File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 378, in call_signature
>     if handler(*args, **kwargs):
>   File "/opt/cuckoo/modules/signatures/windows/antivm_generic_cpu.py", line 32, in on_complete
>     for regkey in self.check_key(pattern=indicator, regex=True, all=True):
>   File "/opt/cuckoo/lib/cuckoo/common/abstracts.py", line 903, in check_key
>     all=all)
>   File "/opt/cuckoo/lib/cuckoo/common/abstracts.py", line 731, in _check_value
>     exp = re.compile(pattern, re.IGNORECASE)
>   File "/usr/lib/python2.7/re.py", line 190, in compile
>     return _compile(pattern, flags)
>   File "/usr/lib/python2.7/re.py", line 244, in _compile
>     raise error, v # invalid expression
> error: unexpected end of regular expression

**Comment by jbremer** [comment]
You are correct, thanks for reporting. Will fix ASAP.
