### ISSUE TITLE
Updating signatures for compatibility issue

### ISSUE THREAD

**Issue by netpacket** [cuckoosandbox/community#312]
I have Cuckoo 2.0.3 and have the majority of yara/powershell signatures coming up with this error: ...Cuckoo  version that's not compatible with this signature. 

I have ran the cuckoo community -b 2.0 and just cuckoo community to update the signatures. Should I wait for the next update or just remove the signatures?

**Comment by netpacket** [comment]
Ah, these signatures require 2.0.4... I guess I need to update cuckoo sandbox. I am closing this issue.

**Comment by jbremer** [comment]
They're for the upcoming version which has not yet been released, please stay tuned! :-)
