### ISSUE TITLE
is the self.add_match function deprecated?

### ISSUE THREAD

**Issue by cssxn** [cuckoosandbox/community#419]
I saw some code using `self.add_match` and `self.has_matchs`

**Comment by doomedraven** [comment]
the easier way to learn all this is do searches for that in community repo to see how they are used ;)

**Comment by cssxn** [comment]
:-1:

**Comment by RicoVZ** [comment]
Hi cssxn,

I do not know of and do not see any `self.add_mach` and `self.has_matches` in the code.
Is it possible you mean `self.mark` and `self.has_marks`?

It is possible that you see usages of both. `self.has_marks` returns True or False, based on if any marks were added by the signature or if a minimum amount of marks exist. So the use case for this is when you used a `return` statement or see if for example, at least 20 marks were made.

Examples of `self.has_marks`
https://github.com/cuckoosandbox/community/blob/master/modules/signatures/network/dead_host.py#L38

https://github.com/cuckoosandbox/community/blob/master/modules/signatures/windows/ransomware_filemodications.py#L37

`self.mark` and any variation of it(mark_ioc, mark_call etc) are used to "mark" any data that matches your signature.

Examples of `self.mark_*`:

`mark_call` - Used in `on_call`. It marks the current call.
https://github.com/cuckoosandbox/community/blob/master/modules/signatures/windows/persistence_registry_fileless.py#L55

`mark_ioc` - Used to mark specific data and add a category and description
https://github.com/cuckoosandbox/community/blob/master/modules/signatures/windows/suspicious_process.py#L24

This is the abstract class that signatures implement. You can see all types of mark methods here and how they should be used.
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/common/abstracts.py#L1206

**Comment by doomedraven** [comment]
ROFL that thumb down xD people who don't want to learn by themselves :D

all funcions related to signatures can be found here
https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/common/abstracts.py#L812

**Comment by cssxn** [comment]
Thanks for answer that! I've already understood. and I made some notes on my blog,

**Comment by cssxn** [comment]
@doomedraven  Tanks for that, I was just thought It should be documented

**Comment by doomedraven** [comment]
@cssxn well that is opensource, you can always help to devs improve documentation if you miss something and what you consider useful, when i don't see something in docu, i just start do searches in repo/greps to see definition in code

**Comment by doomedraven** [comment]
@cssxn mine neither ;) but well drop few words like "hey guys, this stuff would be good to have in docu also help"

**Comment by cssxn** [comment]
@RicoVZ  I found those code that contains `self.match` and `self.has_matches` in here 
`cuckoo-modified-master\docs\book\src\customization\signatures.rst`

**Comment by cssxn** [comment]
Wow！ It‘’s Indeed，Thanks Bro. I missed up
