### ISSUE TITLE
Need Help!!

### ISSUE THREAD

**Issue by cssxn** [cuckoosandbox/community#422]
I want to get the  `ProcessID` of the example when Cuckoo  invoke the `on_call` function. 

assuming the variable `filter_apinames ` contaions `NtOpenProcess`.

I want know whether the `NtOpenProcess` invocation is from the `analysis example` or from other process.

Can Anyone help me How should I do ?

**Comment by RicoVZ** [comment]
Hi cssxn,

Thanks for posting an issue.

The `on_call` received the API call and a process as arguments, as can be seen at: https://github.com/cuckoosandbox/cuckoo/blob/master/cuckoo/common/abstracts.py#L1273.
Both of those are dictionaries containing information. The process dictionary will contain a `pid` and a `process_name` key.

**Comment by cssxn** [comment]
Thanks for answering. I've found the `self.pid` which is what I need.

The `self.pid` is the sample's pid.
