### ISSUE TITLE
Cuckoo as a malware sample repository

### ISSUE THREAD

**Issue by adimenia** [cuckoosandbox/community#437]
Hello
is there a way to use Cuckoo as a malware repository database without using the sandbox capabilities?

**Comment by doomedraven** [comment]
Lol for that you have specific projects, as thezoo, and viper

**Comment by doomedraven** [comment]
Or cert.pl project but i dont remember the name

**Comment by adimenia** [comment]
Those do not scale well,  and does not provide what I'm looking for.

**Comment by doomedraven** [comment]
If they dont do that how do you expect cuckoo to store it without analyze, they will be in pending and you want get what you need not even basic info, if they dont scale well, push improvements ;)

**Comment by adimenia** [comment]
that's why I asked if cuckoo can be used just as a static analysis engine
without the sandbox capabilities.

**Comment by doomedraven** [comment]
Well if ypu modify all logix you can do it, but as any tool you need to modify core, so personally if you have coding skills i would suggest to improve viper/thezoo/etc intead of making cuckoo for it :)

**Comment by jbremer** [comment]
Cuckoo isn't designed to be used as a purely static analysis utility. You'll not find it to be very useful if that's your goal ;-) Closing issue.
