### ISSUE TITLE
Not an issue, but a question. Is there anyway to modify return values of hooked API? 

### ISSUE THREAD

**Issue by alloygoh** [cuckoosandbox/community#460]
I am trying to configure Cuckoo to counter common anti-analysis tricks. Is there anyway to modify the return values of hooked API calls that might allow me to bypass some of those anti-analysis tricks?

**Comment by doomedraven** [comment]
yep, you can do it in monitor https://github.com/cuckoosandbox/monitor

**Comment by alloygoh** [comment]
@doomedraven I can't find anything in the monitor docs that mentions anything about modifying return values. Am I missing something out?

**Comment by doomedraven** [comment]
check return value https://cuckoo-monitor.readthedocs.io/en/latest/hooks.html#available-blocks
but the best it to go with C hooks so you can do whatever you want

**Comment by alloygoh** [comment]
@doomedraven isn't the return just a declaration of its type? or am I misunderstanding it?

**Comment by doomedraven** [comment]
yes is how default hooks declaration works, is why the best to go with C hooks https://cuckoo-monitor.readthedocs.io/en/latest/components.html#c-framework

**Comment by alloygoh** [comment]
@doomedraven so I would have to write custom C code for the APIs that I want to modify its return value?

**Comment by doomedraven** [comment]
yes

**Comment by alloygoh** [comment]
ok thank you for your help!!

**Comment by doomedraven** [comment]
you are welcome

**Comment by alloygoh** [comment]
@doomedraven which source file do I have to modify? I am quite lost at the layout. Or do I have create a new src file? If so, how do I integrate it into the existing source?
Much Thanks!

**Comment by doomedraven** [comment]
well if you could for start say which hook you want to modify

**Comment by alloygoh** [comment]
@doomedraven can't think of one right off my head but let's say its IsDebuggerPresent. How can I go about modifying its return value

**Comment by alloygoh** [comment]
@doomedraven How can I modify the `lpTotalNumberOfFreeBytes` of GetDiskFreeSpaceExW call to 120GB to bypass anti-VM checks my malware?
