### ISSUE TITLE
Signature infostealer_browser.py is inaccurate

### ISSUE THREAD

**Issue by botherder** [cuckoosandbox/community#59]
The signature `infostealer_browser.py` raises way too many false positives and it's causing considerable issues, needs to be fixed.

**Comment by jbremer** [comment]
I think a lot of false positives can be resolved by not caring about the `index.dat` file - does that contain anything useful at all anyway?

**Comment by botherder** [comment]
Has the signature changed?

**Comment by jbremer** [comment]
Not really, aside from changing to the latest Signature API.

**Comment by jbremer** [comment]
I removed the `index.dat` thing as it was causing pretty much only false positives. Guess this can be closed.
