### ISSUE TITLE
Error in Signature banker_zeus_url.py

### ISSUE THREAD

**Issue by threatlead** [cuckoosandbox/community#66]
* Line: https://github.com/cuckoosandbox/community/blob/master/modules/signatures/windows/banker_zeus_url.py#L43

`Traceback (most recent call last):
  File "~/cuckoo/lib/cuckoo/core/plugins.py", line 378, in call_signature
    if handler(*args, **kwargs):
  File "~/cuckoo/modules/signatures/windows/banker_zeus_url.py", line 43, in on_complete
    self.match(None, "url", url=url)
AttributeError: 'ZeusURL' object has no attribute 'match'`

* Based on other samples, this one seems to be using functions no longer supported.

**Comment by botherder** [comment]
Do you have a sample to test it with?

**Comment by threatlead** [comment]
`POST /sliva/gate.php HTTP/1.0
Host: perarnowi.ru
Accept: */*
Accept-Encoding: identity, *;q=0
Accept-Language: en-US
Content-Length: 198
Content-Type: application/octet-stream
Connection: close
Content-Encoding: binary
User-Agent: ...`

**Comment by jbremer** [comment]
I believe this may fix the problem, @threatlead? :-)
Thanks for reporting.
